package test

import (
	gt "github.com/mangenotwork/gathertool"
	"testing"
)

func TestReg(t *testing.T) {
	// 优先检查正则表达式是否报错，程序是否中断
	ctx, _ := gt.Get("https://golang.google.cn/")
	gt.RegFindAllTxt(`(?is:<a.*?</a>)`, ctx.Html)
	gt.RegHtmlA(ctx.Html)
	gt.RegHtmlTitle(ctx.Html)
	gt.RegHtmlKeyword(ctx.Html)
	gt.RegHtmlDescription(ctx.Html)
	gt.RegHtmlTr(ctx.Html)
	gt.RegHtmlInput(ctx.Html)
	gt.RegHtmlTd(ctx.Html)
	gt.RegHtmlP(ctx.Html)
	gt.RegHtmlSpan(ctx.Html)
	gt.RegHtmlSrc(ctx.Html)
	gt.RegHtmlHref(ctx.Html)
	gt.RegHtmlH1(ctx.Html)
	gt.RegHtmlH2(ctx.Html)
	gt.RegHtmlH3(ctx.Html)
	gt.RegHtmlH4(ctx.Html)
	gt.RegHtmlH5(ctx.Html)
	gt.RegHtmlH6(ctx.Html)
	gt.RegHtmlTbody(ctx.Html)
	gt.RegHtmlVideo(ctx.Html)
	gt.RegHtmlCanvas(ctx.Html)
	gt.RegHtmlCode(ctx.Html)
	gt.RegHtmlImg(ctx.Html)
	gt.RegHtmlUl(ctx.Html)
	gt.RegHtmlLi(ctx.Html)
	gt.RegHtmlMeta(ctx.Html)
	gt.RegHtmlSelect(ctx.Html)
	gt.RegHtmlTable(ctx.Html)
	gt.RegHtmlButton(ctx.Html)
	gt.RegHtmlTableOnly(ctx.Html)
	gt.RegHtmlDiv(ctx.Html)
	gt.RegHtmlOption(ctx.Html)

	// 取标签内容
	gt.RegHtmlATxt(ctx.Html)
	gt.RegHtmlTitleTxt(ctx.Html)
	gt.RegHtmlKeywordTxt(ctx.Html)
	gt.RegHtmlDescriptionTxt(ctx.Html)
	gt.RegHtmlTrTxt(ctx.Html)
	gt.RegHtmlTdTxt(ctx.Html)
	gt.RegHtmlPTxt(ctx.Html)
	gt.RegHtmlSpanTxt(ctx.Html)
	gt.RegHtmlSrcTxt(ctx.Html)
	gt.RegHtmlHrefTxt(ctx.Html)
	gt.RegHtmlH1Txt(ctx.Html)
	gt.RegHtmlH2Txt(ctx.Html)
	gt.RegHtmlH3Txt(ctx.Html)
	gt.RegHtmlH4Txt(ctx.Html)
	gt.RegHtmlH5Txt(ctx.Html)
	gt.RegHtmlH6Txt(ctx.Html)
	gt.RegHtmlCodeTxt(ctx.Html)
	gt.RegHtmlUlTxt(ctx.Html)
	gt.RegHtmlLiTxt(ctx.Html)
	gt.RegHtmlSelectTxt(ctx.Html)
	gt.RegHtmlTableTxt(ctx.Html)
	gt.RegHtmlButtonTxt(ctx.Html)
	gt.RegHtmlDivTxt(ctx.Html)
	gt.RegHtmlOptionTxt(ctx.Html)
	gt.RegValue(ctx.Html)

	// 删除
	gt.RegDelHtml(ctx.Html)
	gt.RegDelNumber(ctx.Html)

	// 是否含有
	gt.IsNumber(ctx.Html)
	gt.IsNumber2Len(ctx.Html, 2)
	gt.IsNumber2Heard(ctx.Html, 2)
	gt.IsFloat(ctx.Html)
	gt.IsFloat2Len(ctx.Html, 2)
	gt.IsEngAll(ctx.Html)
	gt.IsEngLen(ctx.Html, 2)
	gt.IsEngNumber(ctx.Html)
	gt.IsLeastNumber(ctx.Html, 2)
	gt.IsLeastCapital(ctx.Html, 2)
	gt.IsLeastLower(ctx.Html, 2)
	gt.IsLeastSpecial(ctx.Html, 2)
	gt.HaveNumber(ctx.Html)
	gt.HaveSpecial(ctx.Html)
	gt.IsEmail(ctx.Html)
	gt.IsDomain(ctx.Html)
	gt.IsURL(ctx.Html)
	gt.IsPhone(ctx.Html)
	gt.IsLandline(ctx.Html)
	gt.AccountRational(ctx.Html)
	gt.IsXMLFile(ctx.Html)
	gt.IsUUID3(ctx.Html)
	gt.IsUUID4(ctx.Html)
	gt.IsUUID5(ctx.Html)
	gt.IsRGB(ctx.Html)
	gt.IsFullWidth(ctx.Html)
	gt.IsHalfWidth(ctx.Html)
	gt.IsBase64(ctx.Html)
	gt.IsLatitude(ctx.Html)
	gt.IsLongitude(ctx.Html)
	gt.IsDNSName(ctx.Html)
	gt.IsIPv4(ctx.Html)
	gt.IsWindowsPath(ctx.Html)
	gt.IsUnixPath(ctx.Html)

	//常用正则
	gt.RegTime(ctx.Html)
	gt.RegLink(ctx.Html)
	gt.RegEmail(ctx.Html)
	gt.RegIPv4(ctx.Html)
	gt.RegIPv6(ctx.Html)
	gt.RegIP(ctx.Html)
	gt.RegMD5Hex(ctx.Html)
	gt.RegSHA1Hex(ctx.Html)
	gt.RegSHA256Hex(ctx.Html)
	gt.RegGUID(ctx.Html)
	gt.RegMACAddress(ctx.Html)
	gt.RegEmail2(ctx.Html)
	gt.RegUUID3(ctx.Html)
	gt.RegUUID4(ctx.Html)
	gt.RegUUID5(ctx.Html)
	gt.RegUUID(ctx.Html)
	gt.RegInt(ctx.Html)
	gt.RegFloat(ctx.Html)
	gt.RegRGBColor(ctx.Html)
	gt.RegFullWidth(ctx.Html)
	gt.RegHalfWidth(ctx.Html)
	gt.RegBase64(ctx.Html)
	gt.RegLatitude(ctx.Html)
	gt.RegLongitude(ctx.Html)
	gt.RegDNSName(ctx.Html)
	gt.RegFullURL(ctx.Html)
	gt.RegURLSchema(ctx.Html)
	gt.RegURLUsername(ctx.Html)
	gt.RegURLPath(ctx.Html)
	gt.RegURLPort(ctx.Html)
	gt.RegURLIP(ctx.Html)
	gt.RegURLSubdomain(ctx.Html)
	gt.RegWinPath(ctx.Html)
	gt.RegUnixPath(ctx.Html)
}
